### ISSUE TITLE
Question about mpii test

### ISSUE THREAD

**Issue by JJBOY** [yangsenius/PoseNFS#1]
Hello, Thanks for your awesome work.
You mentioned that you used the same data preparation with samplebaseline. There is a question confused me a long time. The test.json provided by them only has about 7000 persons. How did you use the json file to generate the final results ?

**Comment by yangsenius** [comment]
Thanks for your interest.
Yes, MPII test set actually contains 7247 person samples. The evaluation procedure https://github.com/yangsenius/PoseNFS/blob/73524a518463bb45877b0169e2a877be587ef565/src/evaluate.py#L242
would generate a `pred.mat` file, but it＇ｓ format does not meet the demand of MPII offiical test. So, I write a MATLAB code to convert it into an appropriate fomat according to the guidelines from [MPII evaluation](http://human-pose.mpi-inf.mpg.de/#evaluation).

**Comment by JJBOY** [comment]
Thanks for your quickly reply! I know we need to use a matlab script to convert the pred.mat. What I want to know is that can we get the correct results only using 7247 samples? In this case, there are many samples are invalid in the offcial's annotation file because it contains about 11000 persons.

**Comment by JJBOY** [comment]
We have tried yo merge the test.json provided by simplebaseline and we converted from official annotation. It can be 0.9% higher in test set than val set. We also tried to write code to on use the 7247 samples to generate the final file(because it would raise error when use the official code with 7247 samples), but get very slow pckh score. So we guess the 7247 samples are not the compelete test set.

**Comment by yangsenius** [comment]
Let me show my MATLAB code, i think it can help you~
```
load('pred.mat')
load('mpii_human_pose_v1_u12_1.mat')
predicted_keypoints = pred;
% pred = a.pred
% imgs_id = a.imgs_id

annolist_test = RELEASE.annolist(RELEASE.img_train == 0);
rectidxs = RELEASE.single_person(RELEASE.img_train == 0);
pred = annolist_test;

body_id = 1;
for imgidx = 1:length(annolist_test)
    rects = rectidxs(imgidx,1);
    ridx = rects{:,1};
    for num = 1:length(ridx)
        rid = ridx(num);
        for point = 1:16
            pred(imgidx).annorect(rid).annopoints.point(point).x ...
                = predicted_keypoints(body_id,point,1);
            
            pred(imgidx).annorect(rid).annopoints.point(point).y ...
                = predicted_keypoints(body_id,point,2);
            
            pred(imgidx).annorect(rid).annopoints.point(point).id ...
                = point-1;    
        end
        body_id = body_id + 1;
    end
end

save('pred_keypoints_mpii.mat','pred');

fprintf("%d",body_id)
```

The test result may be higher 1%~2% than validation result.

**Comment by JJBOY** [comment]
Thanks a lot! I will have a try using your MATLAB code.

**Comment by Chet1996** [comment]
Hello, thanks for sharing your awesome work!!!
I have a more question about the mpii test. There is a "trainval.json" provied by simplebaseline and it is necessary to retrain the model to generate the submission file?

**Comment by yangsenius** [comment]
I don't know whether it is a necessity, because the times for uploads are limited. Ｍａｙｂｅ ｖａｌｉｄａｔｉｏｎ results are more worthy comparing.

**Comment by Chet1996** [comment]
Thanks for your patient reply! It helped me a lot~

**Comment by yuechengyu0710** [comment]
> Let me show my MATLAB code, i think it can help you~
> 
> ```matlab
> load('pred.mat')
> load('mpii_human_pose_v1_u12_1.mat')
> predicted_keypoints = pred;
> % pred = a.pred
> % imgs_id = a.imgs_id
> 
> annolist_test = RELEASE.annolist(RELEASE.img_train == 0);
> rectidxs = RELEASE.single_person(RELEASE.img_train == 0);
> pred = annolist_test;
> 
> body_id = 1;
> for imgidx = 1:length(annolist_test)
>     rects = rectidxs(imgidx,1);
>     ridx = rects{:,1};
>     for num = 1:length(ridx)
>         rid = ridx(num);
>         for point = 1:16
>             pred(imgidx).annorect(rid).annopoints.point(point).x ...
>                 = predicted_keypoints(body_id,point,1);
>             
>             pred(imgidx).annorect(rid).annopoints.point(point).y ...
>                 = predicted_keypoints(body_id,point,2);
>             
>             pred(imgidx).annorect(rid).annopoints.point(point).id ...
>                 = point-1;    
>         end
>         body_id = body_id + 1;
>     end
> end
> 
> save('pred_keypoints_mpii.mat','pred');
> 
> fprintf("%d",body_id)
> ```
> 
> The test result may be higher 1%~2% than validation result.

Thank you for your code,but when i run this matlab code i meet the error it says undefine 'pred' in line 3,how can i solve it ?thank you

**Comment by yangsenius** [comment]
You need to include the `pred.mat` file in the directory path of this code. @yuechengyu0710

**Comment by Github3G** [comment]
> You need to include the `pred.mat` file in the directory path of this code. @yuechengyu0710

In the 3 line of your matlab code, it should be 'predicted_keypoints=preds'.
in addition, i use the test.json(7000+) provided by HRNet to generate pred.mat. then i use your code to convert it for testing. Is that so?

**Comment by yangsenius** [comment]
> In the 3 line of your matlab code, it should be 'predicted_keypoints=preds'.
> in addition, i use the test.json(7000+) provided by HRNet to generate pred.mat. then i use your code to convert it for testing. Is that so?

Yes, you can have a try.

**Comment by Github3G** [comment]
> > In the 3 line of your matlab code, it should be 'predicted_keypoints=preds'.
> > in addition, i use the test.json(7000+) provided by HRNet to generate pred.mat. then i use your code to convert it for testing. Is that so?
> 
> Yes, you can have a try.

thank you patient reply. i use test.json(7000+) and test.json(10000+) to generate pred_mpii_keypoints.mat, the size of two results are same,but i dont know the final testing result is or not same. i also compare the content of two json files and find they are not same in the item of scale and center.  however I trained the network on train.json provided by HRNet.
Does this difference have a significant impact on the test results? Or can i directly submit the pred_mpii_keypoints generated by test.json(7000+) ?look forward to your reply again.

**Comment by yangsenius** [comment]
I use the test.json(7000). The annotation shows that there are 7247 persons in mpii singe-person test set (`rectidxs = RELEASE.single_person(RELEASE.img_train == 0);`).  I don't know the difference between test.json(7000+) and test.json(10000+). You can directly submit the `pred_keypoints_mpii.mat` generated by test.json(7000+). @Github3G

**Comment by Github3G** [comment]
> I use the test.json(7000). The annotation shows that there are 7247 persons in mpii singe-person test set (`rectidxs = RELEASE.single_person(RELEASE.img_train == 0);`). I don't know the difference between test.json(7000+) and test.json(10000+). You can directly submit the `pred_keypoints_mpii.mat` generated by test.json(7000+). @Github3G

Thanks.  10000+ includes the kinds of sample without scale and center annotions, 7000+ filters out the samples. so  whether 10000+ or 7000+, your code will generate same result. In addition, the author of HRNet said there is not difference between 10000+ and 7000+.

**Comment by PCRKTY** [comment]
> > You need to include the `pred.mat` file in the directory path of this code. @yuechengyu0710
> 
> In the 3 line of your matlab code, it should be 'predicted_keypoints=preds'.
> in addition, i use the test.json(7000+) provided by HRNet to generate pred.mat. then i use your code to convert it for testing. Is that so?



> Let me show my MATLAB code, i think it can help you~
> 
> ```matlab
> load('pred.mat')
> load('mpii_human_pose_v1_u12_1.mat')
> predicted_keypoints = pred;
> % pred = a.pred
> % imgs_id = a.imgs_id
> 
> annolist_test = RELEASE.annolist(RELEASE.img_train == 0);
> rectidxs = RELEASE.single_person(RELEASE.img_train == 0);
> pred = annolist_test;
> 
> body_id = 1;
> for imgidx = 1:length(annolist_test)
>     rects = rectidxs(imgidx,1);
>     ridx = rects{:,1};
>     for num = 1:length(ridx)
>         rid = ridx(num);
>         for point = 1:16
>             pred(imgidx).annorect(rid).annopoints.point(point).x ...
>                 = predicted_keypoints(body_id,point,1);
>             
>             pred(imgidx).annorect(rid).annopoints.point(point).y ...
>                 = predicted_keypoints(body_id,point,2);
>             
>             pred(imgidx).annorect(rid).annopoints.point(point).id ...
>                 = point-1;    
>         end
>         body_id = body_id + 1;
>     end
> end
> 
> save('pred_keypoints_mpii.mat','pred');
> 
> fprintf("%d",body_id)
> ```
> 
> The test result may be higher 1%~2% than validation result.

I use your MATLAB code,but it shows :
The index at position 1 exceeds the array boundary (cannot exceed 2958)
error (line  19)                 = predicted_keypoints(body_id,point,1);

How can I fix it? Thank you.

**Comment by PCRKTY** [comment]
> > > In the 3 line of your matlab code, it should be 'predicted_keypoints=preds'.
> > > in addition, i use the test.json(7000+) provided by HRNet to generate pred.mat. then i use your code to convert it for testing. Is that so?
> > 
> > 
> > Yes, you can have a try.
> 
> thank you patient reply. i use test.json(7000+) and test.json(10000+) to generate pred_mpii_keypoints.mat, the size of two results are same,but i dont know the final testing result is or not same. i also compare the content of two json files and find they are not same in the item of scale and center. however I trained the network on train.json provided by HRNet.
> Does this difference have a significant impact on the test results? Or can i directly submit the pred_mpii_keypoints generated by test.json(7000+) ?look forward to your reply again.

Hello, can you tell me how to use generate "pred_mpii_keypoints.mat" using test.json?I'm also running the code of HRNet.
I want to test the model on MPII test-set to get the PCKh scores.  Would you plz explain the correct process to get PCKh score?
I have already got the "pred.mat" which from the output after training the network on train.json.

**Comment by yangsenius** [comment]
This matlab code receives the `pred.mat` and output the `pred_mpii_keypoints.mat`.
It seems that `preds` rather 'pred' appears in HRNet Code's output. @PCRKTY

**Comment by PCRKTY** [comment]
> This matlab code receives the `pred.mat` and outputs the `pred_mpii_keypoints.mat`. Then you just submit the `pred_mpii_keypoints.mat`.
> It seems that `preds` rather 'pred' appears in HRNet Code's output. @PCRKTY

Yes, I have replaced the "pred" with "preds" on line 3, but it shows the error:
The index at position 1 exceeds the array boundary (cannot exceed 2958).
Error  (line 19)
                 = predicted_keypoints(body_id,point,1);
Did I do something wrong?
Thank you for your reply.

**Comment by yangsenius** [comment]
Does your test.json or pred.mat have 7247 person instances? Your error shows that the `pred` only has 2958 persons results.

**Comment by PCRKTY** [comment]
Thank you for your reply @yangsenius 
I noticed I misunderstand the pred.mat which generates by valid.json. 
But I'm confused about how to generate the pred.mat by using test.json because the format of  test.json and valid.json are different which provided by HRNet.
