### ISSUE TITLE
The result on MPII test dataset

### ISSUE THREAD

**Issue by zhangrj91** [yangsenius/PoseNFS#11]
Hi, I think this project is great and thanks for your great work!

We'd like to cite your paper. Would you mind share your results of your model based on HRnet-W32 on MPII test dataset?

Besides, I can't load your pretrained model for MPII validation dataset (PCKh@0.5 = 90.1) to test, could you give me your configuration of this model?

**Comment by yangsenius** [comment]
Hi @zhangrj91. The test result of HRNet-w32-stem-stag3 based model (ours-b) on MPII test is 91.0, which has been shown in the table  V of the [paper](https://arxiv.org/pdf/1909.07068.pdf).

And this repo had a little update. If you want to load the pretrained model, you may need to see [this](https://github.com/yangsenius/PoseNFS/blob/dd8403633b64936e73a3d8d44d4b34f422d6a6a0/src/architecture/meta_cell.py#L73).
