### ISSUE TITLE
mobilenet config not clear

### ISSUE THREAD

**Issue by rlrahulkanojia** [yangsenius/PoseNFS#5]
Please provide config example for mobile net v2.

**Comment by yangsenius** [comment]
I wonder if you have encountered the same problem as [this issue](https://github.com/yangsenius/PoseNFS/issues/4). If so, please refer to it. 
And, if needed, I will provide more config examples in the future.

**Comment by yangsenius** [comment]
I wonder if you have encountered the same problem as this issue. If so, please refer to it.
And, if needed, I will provide more config examples in the future. @rlrahulkanojia
