### ISSUE TITLE
The result on COCO val dataset

### ISSUE THREAD

**Issue by GongXinyuu** [yangsenius/PoseNFS#6]
Hi, thanks for your great work!

We'd like to cite your paper. Would you mind share your results on COCO val dataset?

**Comment by yangsenius** [comment]
Hi, thanks for your interest!

The results on COCO val dataset with 56 AP person detection results are: 
||coco val|Params|FLOPs|
|---|---|---|---|
|Ours-1 | 0.680|6.1M|4.0G|
|Ours-3|0.730|15.8M|14.8G|

Sorry for that I haven't found the history experiment result of the Ours-2 model for coco val set at present. I may add it in the future.

**Comment by GongXinyuu** [comment]
Thank you for your prompt response! BTW, is the input size here 384 * 288?

**Comment by yangsenius** [comment]
Yes. More details are in the paper.
